input = "ACTGAATCTCCCCGACGCCTCTCAGAGCGGAAAGATTTCCGATGCGCATAGGGCGCGTCTCTTCGAATCAAGGCGTCCCATTTTCCAGTGATTTTGTGGCTCTTTCAGGCACTTGGATTCATCTCCGTGCCAGACGTATGCTCTCCTGGGATCGCGTGAGCTATGGAGGAGCCGGCCCTGCCTGTTTAAGCGAGTGCGTGCGGCTTCGCGCTAACCTTCTGTTACGCGGGCTAAAGTCGCTATAGCCCTAGCTGTTTTATGCACACGTGGTACCGATACCCGTAGTAGGCGTCACATTCCAGTGCCGGTGTAGTGTAAGAACCCTGATTAGTGTCACTGCGTCGTAAGTCGGCTTCCAGGGATGGCTTTAGTAGAGTGTAACGCCTATCCGCATACGTAAATTTATTGCGAGATATTAGATCAATGTGGCTTGGATGTAGAAGAGGGGTTTTAGTACATCATATAACCAGTCTCTAAACGGGGCCGCAGCAAGTCAATAGAGTTCTAATACTCAATAGGGGGTCTGCTACGGATCGCACGTACCATGTATCTGGGCAAGCAGGTGCCTCCCCTTTCTCCTACAGTGACGCCGCGCGCAATCCAACACCAGTTTTCCTTAACGACTCGCCACGACAGAACTCTTTTATGTTAAATAAGCTGGCGACTTAGGATGCCGCTGGTCCCATGACTCCACGTCGGGACGACCGTATCATGTGTATACGGTTCGCGTCTAGTACCGAAACCTGGATGTATACTGCTAACTCGGAAGAGTGATGTGCCGGTTATCAGGCACGGTACATGACTCAATGACACATCCGCATGTACTGCCTGCGCTGCTGAGACATTCGCGACACAAAAGAACGACGCTGAAACAAGGGCGCGAGCTAAGGGAGGCGAGACAGCTGACTACACTGTTTAAGTTCCTGGTTCTTCGTCCCTCTCCAGCGCTAGAGTCATTCTGGGAGTGACCCTCACGG"
counter_A = 0
counter_C = 0
counter_G = 0
counter_T = 0

for char in input:
    if char == "A":
        counter_A += 1
    elif char == "C":
        counter_C += 1
    elif char == "G":
        counter_G += 1
    elif char == "T":
        counter_T += 1
    else:
        continue

print(f"{counter_A} {counter_C} {counter_G} {counter_T}"

