input = "GACAAGTAATCTCCGTAACTTCTTCGGGACTACTATTACTGACCTCGCGTGTGTTTTGGCGACCCCCCGACCCTAACAGCCCTGCTCTGATGTAAACGGTGCGCGTAAAGAGAAATCCCGGAGAGTTGATCGAGCGAGTTAATGGCCATTTAGTAGGATCAAATCAACCTTACGACGATCAAGTTCGCCCCTTTCTCCCGCTACGACTCCCATGTTGGAACATCGGGGGTACGTCTGTGGGTCAACCGTAATGTGGCTTCAAGCTTGTATTGCAGATGGAGTTACGTGGCTTTTTATGAGTCCCACCTGAAATAACGTAAGAACAAGAGGTATAGTGCCCTATTGGTATGGGACTGGGAAAGACCACTCGGGCCCGGCCCTGAGGAGCGCTTAATCCACCAAGATGCCTGACCTCCGCGCTTCACATATACGCCGACCGATTAAGTTATTCCGGTAAGGTTTCAGATTTCCTGGTCCCCGTAATGCCATGAGTCTAGATCATCAAAGATACCAAGTGCGAGCCTCCAACACAGAAGCATCCGTTCTCACGACAACTTTACAATACCGCCCACCGTTACAGACAATCGTAGGCAAACATACCGCCGGGAGTATATCGTCTGCCCTTTCCGATAGCATGTTTCCCATCACGAATTCCTTAATAGAGGAAGCGCCGAACTTACAGATCGCGTCCAGCTTAGGCCACCCTCGGGCCAAGTGTTGCCTCTGTGCGAGGGGAATGTTCGGGAGAATCCTCTAAGGGCCTGCCATGGTTCTAGTGACGCTTTGCACAAGCAGGCTAACGAGGGCTTGCGTGGGCTTATAACGAATGGAGGGCGTCGATTCATGGCTCGGCCGGAGCCAA"

complement = ""

for char in input:
    if char == "A":
        complement += "T"
    if char == "C":
        complement += "G"
    if char == "G":
        complement += "C"
    if char == "T":
        complement += "A"

reverse_complement = complement[::-1]

print(reverse_complement)
